- apps/web/components/Footer.tsx
Few text weren't in Title Case, fixed it.
> Changed to Title Case

- Cargo.lock
- apps/web/app/record/Record.tsx
- apps/web/app/record/useRecorder.ts
i wish github supported stacking natively
> merge cap-14

- Cargo.lock
- apps/desktop/src-tauri/Cargo.toml
- apps/desktop/src-tauri/src/main.rs
- apps/desktop/src-tauri/src/utils.rs
- package.json
- pnpm-lock.yaml
Implements the following:
-`winapi` crate for windows, for creating pipes
-Windows / Unix specific `create_named_pipe` function
-Windows / MacOS specific `SystemTray::new()`
-Fixed package.json for Windows
> Improvements + Fixes for Windows

- apps/web/app/api/playlist/route.ts
`/api/playlist` currently lists all media files to construct the playlist. This is slow and error-prone:
1. S3 commands take a while, especially in local dev for me in Australia
2. When `ListObjectsV2Command` is executed, the client may not be done uploading all its files.
I've changed `/api/playlist` to pull the uploaded `stream.m3u8` which is basically guaranteed to exist, and modify all the `segment.ts` entries to be presigned urls. Some of the later segments may not exist when the client goes to load them, but this is something the client needs to be able to handle anyway. Reading one file from S3 rather than making a bunch of requests shaves finish recording -> view in share page time from 8s to 5s for me.
> Use client's stream.m3u8 when generating playlist dynamically

- Cargo.lock
- Cargo.toml
- apps/desktop/package.json
- apps/desktop/src-tauri/Cargo.toml
- apps/desktop/src-tauri/src/main.rs
- apps/desktop/src-tauri/src/media/mod.rs
- apps/desktop/src-tauri/src/utils.rs
- apps/desktop/src-tauri/tauri.conf.json
- apps/desktop/src/components/windows/inner/Recorder.tsx
- crates/tauri-plugin-global-shortcut/Cargo.toml
- crates/tauri-plugin-global-shortcut/guest-js/index.ts
- crates/tauri-plugin-global-shortcut/package.json
- crates/tauri-plugin-global-shortcut/src/error.rs
- crates/tauri-plugin-global-shortcut/src/lib.rs
- crates/tauri-plugin-global-shortcut/tsconfig.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
I've ported `@tauri-apps/plugin-global-hotkey` to mostly work with tauri v1, when we move to v2 it'll be easy to switch.
The hotkeys are disabled at the moment until #53 is merged, after which we can enable/disable/configure them.
- Start: `CommandOrControl+Shift+R`
- Stop: `CommandOrControl+Shift+S`
> implement hotkeys backend with tauri plugin

- README.md
The url to the website was not working.
> fix: fix web url in README.md

- Cargo.lock
- Cargo.toml
- apps/desktop/src-tauri/Cargo.toml
- apps/desktop/src-tauri/src/recording.rs
- crates/media/Cargo.toml
- crates/media/src/encoders/h264.rs
- crates/media/src/encoders/h264_avassetwriter.rs
- crates/media/src/encoders/mod.rs
- crates/media/src/sources/screen_capture.rs
- crates/rendering/src/decoder.rs
- crates/rendering/src/lib.rs
AVAssetWriter + VideoToolbox reduce the CPU cost of screen recording to only ~5%. The quality options could use some adjusting, taking inspiration from OBS to get better quality from a lower bitrate, but it looks pretty good as is.
> Use AVAssetWriter for encoding on macos

- Cargo.lock
- apps/desktop/src-tauri/Cargo.toml
- apps/desktop/src-tauri/src/audio_meter.rs
- apps/desktop/src-tauri/src/lib.rs
- apps/desktop/src-tauri/src/recording.rs
- apps/desktop/src/routes/(window-chrome)/(main).tsx
- apps/desktop/src/utils/tauri.ts
- crates/media/Cargo.toml
- crates/media/src/feeds/audio_input.rs
- crates/media/src/feeds/camera.rs
- crates/media/src/feeds/mod.rs
- crates/media/src/sources/audio_input.rs
- crates/media/src/sources/camera.rs
Adds an indicator of the current mic level, and turns the mic input into a feed similar to the camera.
Closes #151
https://github.com/user-attachments/assets/4d80fdc2-c8ed-461a-a82f-cf4af069862b
> show mic input audio levels

- crates/utils/src/lib.rs
Issue appeared from: https://github.com/CapSoftware/Cap/commit/b64762f51078a6a6eead550b647b8cf94ea12f28
> Fix compile error on macos

- Cargo.lock
- Cargo.toml
- apps/cli/Cargo.toml
- apps/cli/src/main.rs
- apps/cli/src/record.rs
- apps/desktop/scripts/prepare.js
- apps/desktop/src-tauri/src/camera.rs
- apps/desktop/src-tauri/src/lib.rs
- apps/desktop/src-tauri/tauri.conf.json
- crates/editor/src/editor.rs
- crates/media/src/data.rs
- crates/media/src/encoders/h264.rs
- crates/media/src/encoders/h264_avassetwriter.rs
- crates/media/src/encoders/mp3.rs
- crates/media/src/encoders/mp4.rs
- crates/media/src/feeds/camera.rs
- crates/media/src/filters/audio.rs
- crates/media/src/filters/video.rs
- crates/media/src/frame_ws.rs
- crates/media/src/pipeline/builder.rs
- crates/media/src/pipeline/control.rs
- crates/media/src/pipeline/mod.rs
- crates/media/src/pipeline/task.rs
- crates/media/src/sources/audio_input.rs
- crates/media/src/sources/camera.rs
- crates/recording/src/actor.rs
- Simplifies the camera feed such that frames produced by it are raw, leaving conversion to be done somewhere else.
- Adds camera support to the cli via `cap record --camera {index}`
> Camera improvements

- apps/desktop/src-tauri/src/export.rs
- apps/desktop/src-tauri/src/lib.rs
- apps/desktop/src-tauri/src/presets.rs
- apps/desktop/src-tauri/src/recording.rs
- apps/desktop/src/routes/(window-chrome)/licensing.tsx
- apps/desktop/src/routes/(window-chrome)/upgrade.tsx
- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- apps/desktop/src/routes/editor/Editor.tsx
- apps/desktop/src/routes/editor/Header.tsx
- apps/desktop/src/routes/editor/Player.tsx
- apps/desktop/src/routes/editor/context.ts
- apps/desktop/src/routes/editor/projectConfig.ts
- apps/desktop/src/routes/recordings-overlay.tsx
- apps/desktop/src/store.ts
- apps/desktop/src/utils/createPresets.ts
- apps/desktop/src/utils/tauri.ts
- crates/project/src/configuration.rs
- crates/rendering/src/lib.rs
> always use project-configuration.json for exporting

- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- apps/desktop/src/routes/editor/context.ts
Also overhauls the selector to show a preview image
https://github.com/user-attachments/assets/48fda3b4-0229-4ca5-8420-c6d1c296d37a
> remove tab index from manual zoom position selector

- apps/web/app/api/video/domain-info/route.ts
- apps/web/app/globals.css
- apps/web/app/s/[videoId]/Share.tsx
- apps/web/app/s/[videoId]/_components/MP4VideoPlayer.tsx
- apps/web/app/s/[videoId]/_components/ShareHeader.tsx
- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
- apps/web/app/s/[videoId]/_components/VideoPlayer.tsx
- apps/web/app/s/[videoId]/page.tsx
Demo here: https://cap.link/yf3bhrpkaxttw7e
New:
- timeline/play bar scrubbing preview
- improved UI on mobile
- performance fixes on load (fixes double load at beginning)
> feat: Improved video loading/playblack on mobile + thumbnail on seek

- apps/desktop/src/components/Tooltip.tsx
- apps/desktop/src/routes/(window-chrome)/settings/general.tsx
- apps/desktop/src/routes/(window-chrome)/settings/recordings.tsx
- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- apps/desktop/src/routes/editor/Editor.tsx
- apps/desktop/src/routes/editor/Header.tsx
- apps/desktop/src/routes/editor/Player.tsx
- apps/desktop/src/routes/editor/PresetsDropdown.tsx
- apps/desktop/src/routes/editor/ShadowSettings.tsx
- apps/desktop/src/routes/editor/Timeline.tsx
- apps/desktop/src/routes/editor/context.ts
- apps/desktop/src/routes/editor/ui.tsx
- apps/desktop/src/styles/theme.css
- apps/desktop/src/utils/tauri.ts
- apps/web/components/pages/HomePage/index.tsx
- packages/ui-solid/icons/bg-blur.svg
> various editor improvements

- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
**This PR fixes video playback on mobile**:
- Tapping or Dragging anywhere on the time of the video will now happen correctly.
- Prevents scrolling when changing time of the video.
- Minor visual tweaks.
> Fix mobile video playback

- apps/desktop/src/routes/editor/ExportButton.tsx
- apps/desktop/src/routes/editor/ShareButton.tsx
- apps/desktop/src/styles/theme.css
- packages/ui-solid/src/Button.tsx
**This PR**:
- Adds a copy link button in the editor
https://github.com/user-attachments/assets/4cc37229-7f39-4c81-a2dc-2ccb6f8b0cca
> Add copy link button

- apps/desktop/package.json
- apps/desktop/src/routes/(window-chrome)/upgrade.tsx
- apps/desktop/src/routes/editor/Timeline/Track.tsx
- apps/desktop/src/routes/editor/Timeline/ZoomTrack.tsx
- pnpm-lock.yaml
using the remote runtime seems to take ages to load in webkit
> bundle rive runtime instead of loading remote

- apps/desktop/src/routes/editor/ui.tsx
**This PR**:
- Adds hidden pseudo elements to the slider component to increase the area of interactivity.
- Pointer cursor for hovering.
Now it's easier to interact with the slider!
> Improve slider interactivity

- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- apps/desktop/src/routes/editor/Editor.tsx
- apps/desktop/src/routes/editor/ExportDialog.tsx
- apps/desktop/src/routes/editor/context.ts
- apps/desktop/src/routes/editor/ui.tsx
- apps/desktop/src/utils/tauri.ts
- crates/audio/src/renderer.rs
- crates/editor/src/lib.rs
- crates/editor/src/playback.rs
- crates/editor/src/segments.rs
- crates/export/src/lib.rs
- crates/media/src/feeds/audio.rs
- crates/project/src/configuration.rs
- crates/rendering/src/lib.rs
> allow customising stereo behaviour

- apps/desktop/src/routes/editor/ExportDialog.tsx
**This PR**: 
- Makes sure to reset export dialog state on error.
> Reset Export dialog on error

- apps/desktop/src-tauri/src/export.rs
- apps/desktop/src/routes/editor/ExportDialog.tsx
- apps/desktop/src/utils/tauri.ts
> fix file export from ExportDialog

- apps/desktop/src/routes/editor/ExportDialog.tsx
- apps/desktop/src/routes/editor/Header.tsx
- apps/desktop/src/routes/editor/ShareButton.tsx
**This PR**:
- Fixes a minor bug when selecting a resolution
- Upload/export progress is now shown when uploading
- Updated reupload dialog title to Reupload Recording
> Export dialog: upload/export progress + res selection fix

- apps/web/app/dashboard/caps/components/EmptyCapState.tsx
**This PR makes sure the empty state is centered**
> Center empty state

- apps/web/app/dashboard/settings/workspace/Workspace.tsx
- apps/web/app/login/form.tsx
**This PR**: use flex for spacing instead of margins
> Flex based spacing

- Cargo.lock
- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- crates/cursor-capture/Cargo.toml
- crates/cursor-capture/src/lib.rs
- crates/cursor-capture/src/main.rs
- crates/cursor-capture/src/position.rs
- crates/displays/Cargo.toml
- crates/displays/src/lib.rs
- crates/displays/src/main.rs
- crates/displays/src/platform/macos.rs
- crates/displays/src/platform/mod.rs
- crates/displays/src/platform/win.rs
- crates/media/src/sources/screen_capture.rs
- crates/project/src/cursor.rs
- crates/recording/Cargo.toml
- crates/recording/src/cursor.rs
- crates/recording/src/studio_recording.rs
will provide more reliable cursor position recording
> new cursor-capture + displays crates

- apps/web/app/login/form.tsx
This PR tweaks margin login forms, spacing.
> Adjust login form margins

- apps/web/app/dashboard/_components/AdminNavbar/AdminNavItems.tsx
This PR tweaks active state sidebar animation
> Active state sidebar animation

- apps/web/app/dashboard/_components/DashboardInner.tsx
- packages/ui/src/components/Popover.tsx
**This PR**: Improves the dropdown UI of the user
> Improve dropdown UI

- Cargo.lock
- Cargo.toml
- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- apps/desktop/src/routes/editor/ExportDialog.tsx
- crates/export/src/lib.rs
- crates/media/src/encoders/aac.rs
- crates/media/src/encoders/audio.rs
- crates/media/src/encoders/mod.rs
- crates/media/src/encoders/mp4.rs
- crates/recording/src/capture_pipeline.rs
Exported videos will now work in twitter 🤦
> Use AAC audio when exporting

- crates/media/src/encoders/h264.rs
- crates/media/src/sources/screen_capture.rs
Uses more optimal bitrates when encoding with h264 and source resolution when recording on macos
> Encoding quality

- apps/web/actions/videos/delete.ts
- apps/web/app/api/video/delete/route.ts
- apps/web/app/dashboard/caps/Caps.tsx
- apps/web/app/dashboard/caps/components/CapCard.tsx
Adds a multi video deletion flow, and refactor of the delete endpoint to use Next.js actions.
---
- **`apps/web/actions/videos/delete.ts`**  
`deleteVideo()` now deletes the DB record **and** its S3 object with unified error handling.  
- **`apps/web/app/api/video/delete/route.ts`**  
Refactored to delegate work to `deleteVideo()` instead of calling the S3 client directly.
- Multi-select on video cards.  
- Bulk-delete with confirmation dialog and toast feedback.  
- Fixed action bar that shows selected-count and **Delete / Cancel** actions.
- **`CapCard`** now includes a selection checkbox plus refined hover/selected styles.
- Extended `CapCardProps` (`isSelected`, `onSelectToggle`, `anyCapSelected`).  
- Replaced deprecated SVG attributes (`stroke-width` → `strokeWidth`).  
- General …
> Delete multiple caps feature + refactor delete endpoint to action

- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
- apps/web/app/s/[videoId]/_components/tabs/Activity.tsx
- You can now press space on keyboard to play/pause video
- Overlay no longer shows when video is paused
- Animation that shows play or pause state, similar to how Youtube does it
> [CAP-309] Improve video playback experience on web

- apps/web/app/dashboard/caps/Caps.tsx
- apps/web/app/dashboard/caps/components/SelectedCapsBar.tsx
- apps/web/app/dashboard/settings/organization/Organization.tsx
- apps/web/app/dashboard/settings/organization/components/BillingCard.tsx
- apps/web/app/dashboard/settings/organization/components/CustomDomain.tsx
- apps/web/app/dashboard/settings/organization/components/CustomDomainCard.tsx
- apps/web/app/dashboard/settings/organization/components/InviteDialog.tsx
- apps/web/app/dashboard/settings/organization/components/MembersCard.tsx
- apps/web/app/dashboard/settings/organization/components/OrganizationDetailsCard.tsx
- apps/web/app/dashboard/settings/organization/components/SeatsInfoCards.tsx
- apps/web/app/dashboard/shared-caps/SharedCaps.tsx
- apps/web/app/dashboard/shared-caps/page.tsx
- Cleans up organization and Caps by refactoring the JSX And moving code into their own component files.
Make it easier to look at the code in the future.
> Improvement: refactor organization and cleanups

- apps/web/actions/organization/remove-icon.ts
- apps/web/actions/organization/upload-icon.ts
- apps/web/app/dashboard/_components/AdminNavbar/AdminNavItems.tsx
- apps/web/app/dashboard/caps/components/CapCard.tsx
- apps/web/app/dashboard/caps/components/SharingDialog.tsx
- apps/web/app/dashboard/caps/page.tsx
- apps/web/app/dashboard/settings/organization/components/OrganizationIcon.tsx
- apps/web/components/FileInput.tsx
- apps/web/components/forms/NewOrganization.tsx
- apps/web/components/forms/server.ts
- packages/database/migrations/0002_powerful_scourge.sql
- packages/database/migrations/meta/0002_snapshot.json
- packages/database/migrations/meta/_journal.json
- packages/database/schema.ts
- Users can now set org icons for their org in the dashboard
- Fix content shift when editing date of a Cap
> Feat: Support organization icons and fix date content shift editing

- apps/web/app/dashboard/_components/AdminNavbar/AdminDesktopNav.tsx
- apps/web/app/dashboard/_components/AdminNavbar/AdminMobileNav.tsx
- apps/web/app/dashboard/_components/AdminNavbar/AdminNavItems.tsx
- apps/web/app/dashboard/_components/DashboardInner.tsx
- apps/web/app/dashboard/_components/DynamicSharedLayout.tsx
- apps/web/app/dashboard/layout.tsx
- apps/web/app/s/[videoId]/_components/AuthOverlay.tsx
- apps/web/components/UsageButton.tsx
- Sidebar toggle is now based on cookies, clears up errors in terminal and is a better experience overall.
- Mobile had issues with org selector.
- Tapping links on mobile will close the menu + upgrade button.
- Upgrade modal globalized so it does not conflict with nav.
**Todo**: Cleanup some things
> Improvement: mobile responsive fixes, sidebar cookies, and more

- apps/web/app/dashboard/_components/DynamicSharedLayout.tsx
- apps/web/app/dashboard/settings/organization/components/MembersCard.tsx
- packages/ui/src/components/Button.tsx
in this PR instead of using h-screen, it's been changed to dvh instead in CSS so that it takes into account on mobile the browsers search bar and UI.
> Improvement: use dvh better for responsiveness

- apps/web/app/dashboard/_components/AdminNavbar/AdminDesktopNav.tsx
- apps/web/app/dashboard/_components/AdminNavbar/AdminNavItems.tsx
- apps/web/components/UsageButton.tsx
- In comparison to other elements, sidebar was looking off with sizing, especially the links.
- Improved how indicator looks.
- Hover indicator looks better now.
- Improved collapse animation, now other elements bounce a little so it overall it looks more cohesive.
**Todo**: refactor JSX and move different parts into their own file. Far too large right now.
https://github.com/user-attachments/assets/f88ecd18-c968-4e58-b12c-7208eb09f485
> Improve: Sidebar looks

- apps/web/app/dashboard/_components/AdminNavbar/AdminNavItems.tsx
- apps/web/app/dashboard/_components/DashboardInner.tsx
- apps/web/app/dashboard/_components/DynamicSharedLayout.tsx
- apps/web/app/dashboard/caps/components/CapCard.tsx
- apps/web/app/dashboard/caps/components/SelectedCapsBar.tsx
- apps/web/app/dashboard/caps/components/SharingDialog.tsx
- apps/web/components/UsageButton.tsx
- packages/ui/src/components/Card.tsx
- packages/ui/src/components/SkeletonRows.tsx
This PR improves the colors of dashboard, giving it a more premium feel.
> Improvement: Minor Dashboard color changes

- apps/desktop/src/routes/editor/PresetsDropdown.tsx
- apps/desktop/src/utils/createPresets.ts
> fix preset creation

- apps/desktop/src/components/Toggle.tsx
- apps/desktop/src/routes/editor/ConfigSidebar.tsx
- apps/desktop/src/routes/editor/Player.tsx
- apps/desktop/src/routes/editor/PresetsDropdown.tsx
- apps/desktop/src/routes/editor/Timeline/ClipTrack.tsx
- apps/desktop/src/routes/editor/Timeline/Track.tsx
- apps/desktop/src/routes/editor/Timeline/ZoomTrack.tsx
- apps/desktop/src/routes/editor/Timeline/index.tsx
- apps/desktop/src/routes/editor/context.ts
- apps/desktop/src/routes/editor/index.tsx
- apps/desktop/src/routes/editor/ui.tsx
- apps/desktop/src/styles/timeline.css
https://github.com/user-attachments/assets/4ec51313-ee67-4b43-b9d2-c670a1f44cb4
> allow deleting split clips

- crates/cursor-capture/src/position.rs
- fix `with_crop` scaling math in cursor capture
- `cargo test` *(fails: could not fetch git dependency)*
> Fix crop normalization

- apps/desktop/package.json
- apps/desktop/src/App.tsx
- apps/desktop/src/components/CapErrorBoundary.tsx
- apps/desktop/src/routes/(window-chrome)/settings.tsx
- apps/desktop/src/routes/(window-chrome)/settings/integrations/index.tsx
- apps/desktop/src/routes/(window-chrome)/settings/integrations/s3-config.tsx
- apps/web/app/dashboard/caps/components/CapCard.tsx
- packages/ui-solid/src/Button.tsx
- packages/web-api-contract/src/desktop.ts
- pnpm-lock.yaml
- cleaner form management
- tanstack query for mutations
- suspense for loading state
- fix dark theme
> improve s3 connection page

- apps/web/app/api/video/status/route.ts
- apps/web/app/s/[videoId]/Share.tsx
- pnpm-lock.yaml
- Refactor of the Share component to use TanStack Query
- Fixed Cap AI loading state for failed / no transcript
> feat: Refactor of Share.tsx + Cap AI loading state fixes

- apps/desktop/src/routes/editor/ExportDialog.tsx
- crates/rendering/src/layers/cursor.rs
- crates/rendering/src/lib.rs
> make padding and cursor size relative to base resolution, not output

- apps/web/app/dashboard/dashboard-data.ts
- apps/web/app/dashboard/spaces/[spaceId]/components/AddVideosDialogBase.tsx
**This PR**: Only show the spaces that the member has been added to.
> Fix Spaces View

- apps/web/app/dashboard/caps/components/SharingDialog.tsx
- apps/web/app/dashboard/spaces/[spaceId]/components/AddVideosDialogBase.tsx
**This PR**: Improves how the tabs of Sharing dialog looks and a minor visual tweak to the dialog of adding videos to a space.
> Visual tweaks: Sharing dialog and Spaces

- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
**This PR fixes the following issues with video player**:
- When the video reaches the end, it's properly paused with the icons updating.
- When changing the timestamp, no flicking should occur.
> Fix video player bugs

- apps/web/actions/videos/download.ts
- apps/web/app/dashboard/caps/components/CapCard.tsx
Adds a download button to the `CapCard` component.
> Add download video button to dashboard

- apps/web/app/(org)/dashboard/caps/Caps.tsx
- apps/web/app/(org)/dashboard/caps/components/CapCard.tsx
- apps/web/app/s/[videoId]/_components/tabs/Activity.tsx
- apps/web/components/VideoThumbnail.tsx
- packages/ui/src/components/Dropdown.tsx
**This PR**: Moves misc actions of Cap cards into a dropdown to deal with the clutter of UI.
> Actions menu for Cap Card

- apps/web/app/(org)/dashboard/_components/Navbar/Items.tsx
- apps/web/app/(org)/dashboard/settings/organization/Organization.tsx
- apps/web/app/(org)/dashboard/settings/organization/components/CustomDomain.tsx
- apps/web/app/(org)/dashboard/settings/organization/components/CustomDomainIconCard.tsx
- apps/web/app/(org)/dashboard/settings/organization/page.tsx
- packages/ui/src/components/input/Input.tsx
**This PR**:
- Hides org settings from the sidebar and protects the page on the route level if the user is not the owner of the org.
- Minor adjustments to custom domain ui.
> Org settings route protection

- apps/web/app/(org)/dashboard/caps/components/CapCard/CapCard.tsx
**This PR improves the dragging experience of a Cap as seen below**:
https://github.com/user-attachments/assets/42a8a71a-1676-4b25-af7c-8a35b5347809
> improve dragging experience

- apps/web/app/(org)/dashboard/_components/Navbar/Desktop.tsx
**This PR**: Slightly increases animation duration of sidebar for a more comfortable and smooth feeling.
> Sidebar: Increase animation duration

- apps/web/app/(org)/dashboard/caps/Caps.tsx
- apps/web/app/(org)/dashboard/caps/components/NewFolderDialog.tsx
- apps/web/app/(org)/dashboard/caps/components/UploadCapButton.tsx
- apps/web/app/(org)/dashboard/caps/components/UploadPlaceholderCard.tsx
- apps/web/app/(org)/dashboard/folder/[id]/components/FolderVideosSection.tsx
- apps/web/app/(org)/dashboard/folder/[id]/components/UploadCapButtonWithFolder.tsx
**This PR**: makes minor cleanups and adjusts upload progress.
> improvement: Upload cleanups

- apps/web/app/embed/[videoId]/_components/EmbedVideo.tsx
- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
- apps/web/components/pages/HomePage/RecordingModes.tsx
**This PR**: 
- Improve seeking, should be able drag and seek globally, this improves UX. Before, if your mouse slightly exceeds the height of the timeline seeking would stop.
> fix: improve videos ux

- apps/web/components/forms/NewOrganization.tsx
Only set uploading state to true if there's a selected file.
> chore: file uploading state

- apps/web/app/(org)/dashboard/caps/components/SharingDialog.tsx
- apps/web/app/s/[videoId]/_components/ShareHeader.tsx
- apps/web/app/s/[videoId]/page.tsx
> Revert "fix: Fix share dialog from video share page"

- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
**This PR**: Thumb should be correctly positioned in the beginning and end.
> fix: video player fixes

- apps/web/app/s/[videoId]/_components/AuthOverlay.tsx
- apps/web/app/s/[videoId]/_components/tabs/Activity.tsx
**This PR**: Temporary adjustments for the share page, specifically sign in to comment, before I make it into something decent like the login form.
> design: Visual adjustments to sign in to comment

- apps/web/app/(site)/blog/[slug]/page.tsx
- apps/web/app/(site)/docs/[...slug]/page.tsx
- apps/web/app/(site)/docs/[slug]/page.tsx
- apps/web/app/(site)/docs/_components/DocPage.tsx
- apps/web/app/(site)/features/FeaturesPage.tsx
- apps/web/app/(site)/privacy/page.tsx
- apps/web/app/(site)/tools/convert/page.tsx
- apps/web/components/blog/BlogTemplate.tsx
- apps/web/components/pages/DocsPage.tsx
- apps/web/components/pages/DownloadPage.tsx
- apps/web/components/pages/FaqPage.tsx
- apps/web/components/pages/HomePage/Header.tsx
- apps/web/components/pages/PricingPage.tsx
- apps/web/components/pages/TermsPage.tsx
- apps/web/components/pages/TestimonialsPage.tsx
- apps/web/components/pages/UpdatesPage.tsx
- apps/web/components/seo/SeoPageTemplate.tsx
- apps/web/components/tools/ToolsPageTemplate.tsx
**This PR**: A recent PR and fix of the navbar has caused paddings to be off for pages, now it's corrected.
> chore: padding adjustments

- apps/web/app/s/[videoId]/page.tsx
**This PR**: Merged to test on social media platforms
> improvement: embed videos

- README.md
- apps/web/app/api/playlist/route.ts
- apps/web/app/embed/[videoId]/_components/EmbedVideo.tsx
- apps/web/app/s/[videoId]/_components/ShareVideo.tsx
This PR reverts a previously merged  #805.
Changes:
> Revert #805

- apps/desktop/src/routes/(window-chrome)/(main).tsx
- apps/desktop/src/routes/editor/Header.tsx
- apps/web/actions/organizations/add-videos.ts
- apps/web/actions/organizations/remove-videos.ts
- apps/web/app/(org)/dashboard/caps/Caps.tsx
- apps/web/app/(org)/dashboard/caps/page.tsx
- apps/web/app/(org)/dashboard/spaces/[spaceId]/components/AddVideosDialogBase.tsx
- packages/ui-solid/src/Button.tsx
- packages/ui/src/components/Button.tsx
**This PR**: Fixes adding videos to "All" spaces of an org.
> fix: adding videos to "all" spaces

- apps/web/app/(org)/dashboard/_components/LoadingSpinner.tsx
- apps/web/app/(org)/dashboard/spaces/[spaceId]/components/AddVideosDialogBase.tsx
- packages/ui/src/components/Button.tsx
- packages/ui/src/components/LoadingSpinner.tsx
- packages/ui/src/index.tsx
**This PR**: Adds a better loading spinner, it's a generic one. Will make a custom one later.
> chore: better loading spinner

- apps/desktop/src/routes/(window-chrome)/(main).tsx
**This PR**: Fixes the icon color of instant mode in desktop app for when recording.
> fix: Instant icon color

- apps/web/actions/videos/generate-ai-metadata.ts
- apps/web/actions/videos/get-status.ts
- apps/web/app/api/video/ai/route.ts
- apps/web/app/api/video/transcribe/status/route.ts
- apps/web/app/s/[videoId]/Share.tsx
- apps/web/lib/transcribe.ts
**TLDR**: restored some previous code, need to revisit this + for UI sort of generation look and feel of the generated AI data I'd like to make better UI.
> chore: remove console log
